name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Only run when main is updated

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'  # Prevent recursive triggers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Deploy with fine-grained token
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Create clean gh-pages folder
          mkdir gh-pages
          cp -r .output/public/* gh-pages/

          cd gh-pages
          git init
          git remote add origin https://x-access-token:${{ secrets.FG_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push -f origin gh-pages

