name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your source branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Deploy with FG token
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Create temp dir for gh-pages
          mkdir gh-pages

          # Move build files into gh-pages
          cp -r dist/* gh-pages/

          cd gh-pages
          git init
          git remote add origin https://x-access-token:${{ secrets.FG_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b gh-pages
          git add .
          git commit -m "Initial GitHub Pages deploy"
          git push -f origin gh-pages

