name: Deploy SolidJS to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (adjust the version if needed)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 3: Install esbuild version 0.24.2 to resolve version conflicts
    - name: Install esbuild version 0.24.2
      run: npm install esbuild@0.24.2 --save-dev

    # Step 4: Install crypto-browserify to polyfill crypto.getRandomValues
    - name: Install crypto-browserify
      run: npm install crypto-browserify

    # Step 5: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 6: Build the project
    - name: Build the project
      run: npm run build

    # Step 7: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      run: |
        # Make sure we're in the build output folder
        mkdir gh-pages
        cp -r .output/public/* gh-pages/

        # Go to gh-pages folder and set up git
        cd gh-pages
        git init
        git remote add origin https://x-access-token:${{ secrets.FG_TOKEN }}@github.com/napiergit/my-app.git
        git checkout -b gh-pages  # Ensure we're on the correct branch
        git add .
        git commit -m "Deploy to GitHub Pages"

        # Push changes to gh-pages branch
        git push -f origin gh-pages

    # Step 8: Add .nojekyll to bypass Jekyll processing (optional)
    - name: Add .nojekyll
      run: |
        touch gh-pages/.nojekyll
        cd gh-pages
        git add .nojekyll
        git commit -m "Add .nojekyll to bypass Jekyll processing"
        git push origin gh-pages

